inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2.4
  SuggestExtensions: false
  NewCops: enable
  Exclude:
  - 'db/schema.rb'
  - 'db/seeds.rb'
  - 'db/migrate/*.rb'
  - 'bin/**/*'
  - 'vendor/bundle/**/*'
  - 'node_modules/**/*'
  - 'lib/settingslogic.rb'

Layout/LineLength:
  Max: 150
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  CountAsOne: ['array', 'hash']

Metrics/BlockLength:
  Exclude:
  - 'spec/**/*.rb'

Style/NumericLiterals:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/SpaceAroundMethodCallOperator:
  Enabled: false

Lint/RedundantSplatExpansion:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false
