FROM latera/homs_base:latest

USER root

RUN apt-get update && apt-get install -y \
  libfreetype6 \
  libfreetype6-dev \
  libfontconfig1 \
  libfontconfig1-dev \
  libqtwebkit-dev \
  zip

RUN apt-get update && apt-get install -y \
  qt5-default \
  libqt5webkit5-dev \
  gstreamer1.0-plugins-base \
  gstreamer1.0-tools \
  gstreamer1.0-x \
  xvfb \
  fonts-liberation \
  libappindicator3-1 \
  libasound2 \
  libnspr4 \
  libnss3 \
  libxss1 \
  xdg-utils \
  chromedriver

RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && dpkg -i google-chrome-stable_current_amd64.deb

COPY ./run_tests.sh /

RUN chown -R homs:homs /run_tests.sh /opt/homs/config/
RUN chmod +x /run_tests.sh

USER homs
RUN bundle --with test --without oracle

ENTRYPOINT ["/run_tests.sh"]
