version: '2'
services:
  db_activiti:
    image: postgres:11.0
    hostname: postgres-activiti
    container_name: postgres-activiti
    restart: always
    environment:
      PGDATA: $BPM_DB_PATH/activiti
      POSTGRES_DB: $BPM_DB_NAME
      POSTGRES_USER: $BPM_DB_USER
      POSTGRES_PASSWORD: $BPM_DB_PASSWORD
      TZ: Europe/Moscow
    volumes:
      - $HOMS_PATH/data/activiti/postgresql:$BPM_DB_PATH
    networks:
      - custom_network
  db_homs:
    image: postgres:11.0
    hostname: postgres-homs
    container_name: postgres-homs
    restart: always
    environment:
      PGDATA: $HOMS_DB_PATH/homs
      POSTGRES_DB: $HOMS_DB_NAME
      POSTGRES_USER: $HOMS_DB_USER
      POSTGRES_PASSWORD: $HOMS_DB_PASSWORD
      TZ: Europe/Moscow
    volumes:
      - $HOMS_PATH/data/homs/postgresql:$HOMS_DB_PATH
    ports:
      - $HOMS_DB_PORT:5432
    networks:
      - custom_network
  activiti:
    image: latera/activiti-homs
    container_name: activiti
    env_file:
      - ".env"
    links:
      - db_activiti:$BPM_DB_HOST
    environment:
      DB_HOST: $BPM_DB_HOST
      ACTIVITI_LOGIN: $BPM_USER
      ACTIVITI_PASSWORD: $BPM_PASSWORD
    ports:
      - $BPM_PORT:8080
    depends_on:
      - db_activiti
    networks:
      - custom_network
  minio:
    image: minio/minio
    container_name: minio
    command: "server /opt/minio"
    restart: always
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    volumes:
      - $HOMS_PATH/data/minio:/opt/minio
    ports:
      - $MINIO_PORT:9000
  homs:
    image: latera/homs
    hostname: homs
    container_name: homs
    env_file:
      - ".env"
    links:
      - db_homs:$HOMS_DB_HOST
      - activiti:$BPM_HOST
    depends_on:
      - db_homs
      - activiti
      - minio
    ports:
      - $HOMS_PORT:3000
    networks:
      - custom_network
networks:
  custom_network:
    driver: bridge
