FROM latera/homs_base:latest

USER root

RUN apt-get update && apt-get install -y \
  libfreetype6 \
  libfreetype6-dev \
  libfontconfig1 \
  libfontconfig1-dev \
  libqtwebkit-dev \
  zip

RUN apt-get update && apt-get install -y \
  gstreamer1.0-plugins-base \
  gstreamer1.0-tools \
  gstreamer1.0-x \
  fonts-liberation \
  libappindicator3-1 \
  libasound2 \
  libnspr4 \
  libnss3 \
  libxss1 \
  libxtst6 \
  xdg-utils \
  unzip

RUN wget https://dl.google.com/linux/direct/google-chrome-beta_current_amd64.deb && dpkg -i google-chrome-beta_current_amd64.deb
RUN wget https://chromedriver.storage.googleapis.com/74.0.3729.6/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip chromedriver -d /usr/bin/ && \
    chmod +x /usr/bin/chromedriver

COPY ./run_tests.sh ./.rubocop.yml ./.rubocop_todo.yml /
COPY ./.rubocop.yml ./.rubocop_todo.yml  /opt/homs/

RUN chown -R homs:homs /run_tests.sh /opt/homs/config/
RUN chmod +x /run_tests.sh

USER homs
RUN bundle --with test --without oracle

ENTRYPOINT ["/run_tests.sh"]
