name: CI

on:
  push:
    branches: [v2.7]
  pull_request:
    branches: [v2.7]

jobs:
  run-homs-ci:

    runs-on: ubuntu-latest

    steps:
      - name: run homs ci
        run: gh workflow run ci.yml --repo hydra-billing/homs-ci -f branch=${{ github.head_ref || github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.HYDRA_BILLING_ROBOT_TOKEN }}
